"""admin portal tables

Revision ID: 13e08406c163
Revises: 8280d5c403d5
Create Date: 2026-09-08 20:56:05.602589

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '13e08406c163'
down_revision: Union[str, Sequence[str], None] = '8280d5c403d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('factories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('owner_name', sa.String(), nullable=False),
    sa.Column('owner_contact', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('plan_tier', sa.String(), nullable=True),
    sa.Column('enrolled_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['owners.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_id')
    )
    # Backfill: any Owner that signed up before this migration existed
    # needs a matching Factory row too, same as new signups get from
    # main.py's signup() -- otherwise pre-existing factories would be
    # invisible in the admin portal until their owner did something to
    # re-trigger creation (which nothing ever would).
    op.execute(
        """
        INSERT INTO factories (owner_id, name, owner_name, owner_contact, status, enrolled_at)
        SELECT id, factory_name, name, mobile, 'trial', created_at
        FROM owners
        WHERE id NOT IN (SELECT owner_id FROM factories)
        """
    )
    op.create_table('factory_employee_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('factory_id', sa.Integer(), nullable=False),
    sa.Column('month', sa.String(), nullable=False),
    sa.Column('active_employee_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['factory_id'], ['factories.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('factory_id', 'month', name='uq_snapshot_factory_month')
    )
    op.create_table('factory_payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('factory_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('paid_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['factory_id'], ['factories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('factory_payments')
    op.drop_table('factory_employee_snapshots')
    op.drop_table('factories')
    op.drop_table('admin_user')
    # ### end Alembic commands ###
