"""initial schema

Revision ID: 8280d5c403d5
Revises: 
Create Date: 2026-09-07 04:58:28.967255

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import crypto


# revision identifiers, used by Alembic.
revision: str = '8280d5c403d5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('owners',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('mobile', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('factory_name', sa.String(), nullable=False),
    sa.Column('factory_address', sa.String(), nullable=True),
    sa.Column('factory_licence_no', sa.String(), nullable=True),
    sa.Column('consent_given_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mobile')
    )
    op.create_table('portal_credentials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('portal_username', crypto.EncryptedString(), nullable=False),
    sa.Column('portal_password', crypto.EncryptedString(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['owners.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_id')
    )
    op.create_table('shift_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('slot_key', sa.String(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('start_time', sa.String(), nullable=True),
    sa.Column('end_time', sa.String(), nullable=True),
    sa.Column('rest_interval', sa.String(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['owners.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_id', 'slot_key', name='uq_shift_owner_slot')
    )
    op.create_table('worker_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('default_rate_type', sa.String(), nullable=False),
    sa.Column('default_rate', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['owners.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_id', 'name', name='uq_worker_type_owner_name')
    )
    op.create_table('workers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('mobile', sa.String(), nullable=True),
    sa.Column('dob', sa.Date(), nullable=True),
    sa.Column('gender', sa.String(), nullable=True),
    sa.Column('worker_type_id', sa.Integer(), nullable=True),
    sa.Column('aadhaar_last4', sa.String(length=4), nullable=False),
    sa.Column('aadhaar_encrypted', crypto.EncryptedString(), nullable=False),
    sa.Column('current_address', crypto.EncryptedString(), nullable=True),
    sa.Column('current_district', crypto.EncryptedString(), nullable=True),
    sa.Column('native_address', crypto.EncryptedString(), nullable=True),
    sa.Column('native_district', crypto.EncryptedString(), nullable=True),
    sa.Column('bank_account_number', crypto.EncryptedString(), nullable=True),
    sa.Column('bank_ifsc', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('deactivated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deactivated_reason', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['owners.id'], ),
    sa.ForeignKeyConstraint(['worker_type_id'], ['worker_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('attendance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('worker_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('slot', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('overtime_hours', sa.Float(), nullable=False),
    sa.Column('marked_by', sa.Integer(), nullable=False),
    sa.Column('marked_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['marked_by'], ['owners.id'], ),
    sa.ForeignKeyConstraint(['worker_id'], ['workers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('worker_id', 'date', 'slot', name='uq_attendance_slot')
    )
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('worker_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['owners.id'], ),
    sa.ForeignKeyConstraint(['worker_id'], ['workers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('form_generation_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('worker_id', sa.Integer(), nullable=True),
    sa.Column('form_code', sa.String(), nullable=False),
    sa.Column('period_label', sa.String(), nullable=True),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('generated_by', sa.Integer(), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['generated_by'], ['owners.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['owners.id'], ),
    sa.ForeignKeyConstraint(['worker_id'], ['workers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('leave_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('worker_id', sa.Integer(), nullable=False),
    sa.Column('leave_type', sa.String(), nullable=False),
    sa.Column('date_from', sa.Date(), nullable=False),
    sa.Column('date_to', sa.Date(), nullable=False),
    sa.Column('days', sa.Float(), nullable=False),
    sa.Column('wages_paid', sa.Float(), nullable=True),
    sa.Column('marked_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['marked_by'], ['owners.id'], ),
    sa.ForeignKeyConstraint(['worker_id'], ['workers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sync_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('worker_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('last_attempted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['worker_id'], ['workers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('wage_payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('worker_id', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('date_of_payment', sa.Date(), nullable=True),
    sa.Column('payment_reference', sa.String(), nullable=True),
    sa.Column('recorded_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['recorded_by'], ['owners.id'], ),
    sa.ForeignKeyConstraint(['worker_id'], ['workers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('worker_id', 'month', 'year', name='uq_wage_payment_period')
    )
    op.create_table('wage_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('worker_id', sa.Integer(), nullable=False),
    sa.Column('rate_type', sa.String(), nullable=False),
    sa.Column('basic', sa.Float(), nullable=False),
    sa.Column('hra', sa.Float(), nullable=False),
    sa.Column('da', sa.Float(), nullable=False),
    sa.Column('other_allowances', sa.Float(), nullable=False),
    sa.Column('pf_rate', sa.Float(), nullable=False),
    sa.Column('esi_rate', sa.Float(), nullable=False),
    sa.Column('lwf_amount', sa.Float(), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['owners.id'], ),
    sa.ForeignKeyConstraint(['worker_id'], ['workers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('worker_compliance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('worker_id', sa.Integer(), nullable=False),
    sa.Column('worker_code', sa.String(), nullable=True),
    sa.Column('father_or_spouse_name', sa.String(), nullable=True),
    sa.Column('designation_or_nature_of_work', sa.String(), nullable=True),
    sa.Column('epf_uan_no', sa.String(), nullable=True),
    sa.Column('esic_no', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('fitness_cert_no', sa.String(), nullable=True),
    sa.Column('fitness_cert_valid_till', sa.Date(), nullable=True),
    sa.Column('date_of_joining', sa.Date(), nullable=True),
    sa.Column('date_made_permanent', sa.Date(), nullable=True),
    sa.Column('suspension_period', sa.String(), nullable=True),
    sa.Column('registered_by', sa.Integer(), nullable=False),
    sa.Column('registered_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['registered_by'], ['owners.id'], ),
    sa.ForeignKeyConstraint(['worker_id'], ['workers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('worker_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('worker_compliance')
    op.drop_table('wage_profiles')
    op.drop_table('wage_payments')
    op.drop_table('sync_status')
    op.drop_table('leave_entries')
    op.drop_table('form_generation_log')
    op.drop_table('audit_log')
    op.drop_table('attendance')
    op.drop_table('workers')
    op.drop_table('worker_types')
    op.drop_table('shift_configs')
    op.drop_table('portal_credentials')
    op.drop_table('owners')
    # ### end Alembic commands ###
