"""form templates and owner state

Revision ID: 83fef8a9e1ba
Revises: a1348acb7952
Create Date: 2026-09-10 07:32:54.048199

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '83fef8a9e1ba'
down_revision: Union[str, Sequence[str], None] = 'a1348acb7952'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('form_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('form_code', sa.String(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('is_available', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('state', 'form_code', name='uq_form_template_state_code')
    )
    op.add_column('owners', sa.Column('state', sa.String(), nullable=True))
    # ### end Alembic commands ###

    # Seed data, not schema -- Tamil Nadu's rows point at forms.py's
    # already-implemented build_* functions; Karnataka is stubbed
    # (is_available=False) per the explicit "placeholder for now" scope.
    form_templates = sa.table(
        "form_templates",
        sa.column("state", sa.String),
        sa.column("form_code", sa.String),
        sa.column("label", sa.String),
        sa.column("is_available", sa.Boolean),
    )
    op.bulk_insert(
        form_templates,
        [
            {"state": "Tamil Nadu", "form_code": "attendance", "label": "Attendance Report (all workers)", "is_available": True},
            {"state": "Tamil Nadu", "form_code": "form25", "label": "Form 25 — Muster Roll (all workers)", "is_available": True},
            {"state": "Tamil Nadu", "form_code": "form25b", "label": "Form 25-B — Time Card", "is_available": True},
            {"state": "Tamil Nadu", "form_code": "form12", "label": "Form 12 — Register of Adult Workers", "is_available": True},
            {"state": "Tamil Nadu", "form_code": "form15", "label": "Form 15 — Wage Register (all workers)", "is_available": True},
            {"state": "Tamil Nadu", "form_code": "wageslip", "label": "Wage Slip", "is_available": True},
            {"state": "Karnataka", "form_code": "form11", "label": "Form 11 — Register of Employees (coming soon)", "is_available": False},
            {"state": "Karnataka", "form_code": "form14", "label": "Form 14/15 — Wage Register (coming soon)", "is_available": False},
            {"state": "Karnataka", "form_code": "form22", "label": "Form 22 — Register of Wages (coming soon)", "is_available": False},
        ],
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('owners', 'state')
    op.drop_table('form_templates')
    # ### end Alembic commands ###
