"""biometric attendance sync layer

Revision ID: a1348acb7952
Revises: 13e08406c163
Create Date: 2026-09-09 07:19:38.592035

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1348acb7952'
down_revision: Union[str, Sequence[str], None] = '13e08406c163'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('biometric_devices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('ip_address', sa.String(), nullable=False),
    sa.Column('port', sa.Integer(), nullable=False),
    sa.Column('force_udp', sa.Boolean(), nullable=False),
    sa.Column('comm_password', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('last_sync_status', sa.String(), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['owners.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('biometric_consents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('worker_id', sa.Integer(), nullable=False),
    sa.Column('consented_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('consented_by', sa.Integer(), nullable=False),
    sa.Column('notice_text', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['consented_by'], ['owners.id'], ),
    sa.ForeignKeyConstraint(['worker_id'], ['workers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('worker_id')
    )
    op.create_table('biometric_punches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('worker_id', sa.Integer(), nullable=True),
    sa.Column('raw_device_user_id', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('punch_type', sa.String(), nullable=False),
    sa.Column('synced_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['biometric_devices.id'], ),
    sa.ForeignKeyConstraint(['worker_id'], ['workers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('device_id', 'raw_device_user_id', 'timestamp', name='uq_punch_dedup')
    )
    op.create_table('device_user_mapping',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('device_user_id', sa.String(), nullable=False),
    sa.Column('worker_id', sa.Integer(), nullable=False),
    sa.Column('enrolled_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['biometric_devices.id'], ),
    sa.ForeignKeyConstraint(['worker_id'], ['workers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('device_id', 'device_user_id', name='uq_device_user')
    )
    op.add_column('attendance', sa.Column('source', sa.String(), nullable=True))
    op.add_column('attendance', sa.Column('source_detail', sa.String(), nullable=True))
    # Batch mode: SQLite can't ALTER a table to add a column + unique
    # constraint in separate direct statements the way Postgres can --
    # it needs the copy-and-move strategy batch mode provides, which
    # works identically (and more simply, via direct ALTER) on Postgres
    # too, so this is the portable form for both, not a SQLite-only
    # workaround.
    with op.batch_alter_table('workers') as batch_op:
        batch_op.add_column(sa.Column('numeric_employee_code', sa.String(), nullable=True))
        batch_op.create_unique_constraint('uq_worker_employee_code', ['owner_id', 'numeric_employee_code'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workers') as batch_op:
        batch_op.drop_constraint('uq_worker_employee_code', type_='unique')
        batch_op.drop_column('numeric_employee_code')
    op.drop_column('attendance', 'source_detail')
    op.drop_column('attendance', 'source')
    op.drop_table('device_user_mapping')
    op.drop_table('biometric_punches')
    op.drop_table('biometric_consents')
    op.drop_table('biometric_devices')
    # ### end Alembic commands ###
