"""owner industry

Revision ID: e15fb0d97995
Revises: 83fef8a9e1ba
Create Date: 2026-09-14 06:04:44.409448

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e15fb0d97995'
down_revision: Union[str, Sequence[str], None] = '83fef8a9e1ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('owners', sa.Column('industry', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('owners', 'industry')
    # ### end Alembic commands ###
